language: clojure
matrix:
  include:
    - jdk: openjdk12
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
after_success:
  - lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
notifications:
  slack:
    secure: JT16kBQQwYJ72c6HBrQnPuWGvJ51Po4vdqNmV1WIIpJshxyzTDx2rdINkw06hGPvZmycHvueOdupVmVYA5FOQszDT7nfPckw5uyKGxPppTMnWwFaW4TMxLAnweg0XY2bl6PJbM+umxWtb3C892sR1c6SO21tZF0uJmpbbhikYLWVqTBdogFNUbRmowXMnPXZNu4/l14NXSbjT+xd31ghkzRnZ4QBCIhx8Onq4amZhORZyAFA81wf/nZ36Lhszza2KG6Qap71LsYQKfI5Y68CbkiSvgbHw1ZpEUTmhs1OWHVfUvAy3DkEIMjZTi8KQFIUohprMfseY0LgwccTMUobiZwSS6BQhdEvBXIGLHmWFl7W9nNsO7rH/0JQzX8qNdD/2lDDqmwn+7r8BdWcarvmXEDdHHeAtfYs5cjB1uZvJ6rDKW/RY6kWojAXCGU+co+VROu4WYgMxEHRxMz+Df7Lq5l5wkCnp4TkZBoE/+B7g4LZxFnbwiyROk8UOTfd4QpJW9mdg1SqFNNyMSiRc5Nlv73J61qSoXXjS3unICql1jX06aRuOl4bzDqBnmbLO4R3G3ZjM0h0y8gJnJqIZsf0LR0S8RvsyyKqrUqaCBgoaqw34hoLXzBSJTlqCr3IQ/xQe7jqsPvhr0VzZFMOk6TX9QflcFl6IptmDkHDmbcrG34=
